### ISSUE TITLE
TODO v1

### ISSUE THREAD

**Issue by metiftikci** [ankareport/designer#1]
- [ ] Save & Load Layout by JSON Data
- [ ] Make report resizable (width)
- [ ] Make report section resizable (height)
- [ ] Improve Report Item Selector (resize)
- [ ] Improve Toolbar
- [ ] Improve Menu (undo, redo, alignments)
- [ ] Properties panel
- [ ] Data Source panel
- [ ] Report Elements panel
